### ISSUE TITLE
a mistake in update_cert.sh

### ISSUE THREAD

**Issue by wang33winner** [ryecoaaron/scripts#1]
#cp -v "${cert}" "${OMV_SSL_CERTIFICATE_DIR}/certs/${OMV_SSL_CERTIFICATE_PREFIX}-${uuid}.crt"
#cp -v "${key}" "${OMV_SSL_CERTIFICATE_DIR}/private/${OMV_SSL_CERTIFICATE_PREFIX}-${uuid}.key"
shoud be 
cp -v "${cert}" "${OMV_SSL_CERTIFICATE_DIR}/certs/${OMV_SSL_CERTIFICATE_PREFIX}${uuid}.crt"
cp -v "${key}" "${OMV_SSL_CERTIFICATE_DIR}/private/${OMV_SSL_CERTIFICATE_PREFIX}${uuid}.key"

${OMV_SSL_CERTIFICATE_PREFIX} already has `-` in it

**Comment by ryecoaaron** [comment]
While you are correct, these lines are commented out because the files are recreated by saltstack from the contents of the database.  So, there is no need to copy the files.  I will just remove the lines.
